### ISSUE TITLE
B_GITHUBVER

### ISSUE THREAD

**Issue by tails2k** [mverboom/build#6]
Deliver Error: Version command for ....... returned no output.

**Comment by mverboom** [comment]
Any information on which recipe and what command you ran?

**Comment by tails2k** [comment]
Yeah, Recipe is from https://github.com/Thulium-Drake/trinitycore-recipes
Its in all Recipes there, i have look for some errors in it but dont find one: 
[VERSION]
B_GITHUBVER https://github.com/TrinityCore/TrinityCore/tree/3.3.5

**Comment by mverboom** [comment]
Ok, best would be to contact Thulium-Drake, because I'm note sure what he is trying to do with the recipe. However, you can try something like this:
`B_GITVER -D -i "^TDB335" -F "^TDB335." https://github.com/TrinityCore/TrinityCore`
I'm not familiar with TrinityCore, but this might be the right version number. 
BTW, it is not mandatory to use the built in functions to get a version numbers. It can be any code, so if this is not what you are after, you can create your own code to generate the version number.

**Comment by tails2k** [comment]
Thanks it works! I have not read this way of in your Commandlist.

**Comment by mverboom** [comment]
You can find the syntax in BUILD.md file, the part on B_GITVER.
